name: Node.js CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  #build:
  #    runs-on: ${{ matrix.os }}
  #    strategy:
  #      matrix:
  #        node-version: [18.2.0]
  #        os: [ubuntu-latest]
  #    steps:
  #    - uses: actions/checkout@v2
  #    - name: Use Node.js ${{ matrix.node-version }}
  #      uses: actions/setup-node@v2
  #      with:
  #        node-version: ${{ matrix.node-version }}
  #        cache: 'npm'
  #    - run: npm ci
  #    - run: npm run build
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.2.0]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test    
  sonarcloud:
    needs: [run_tests, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get master
        run: git fetch origin master
      - name: Install dependencies
        run:  npm ci
      - name: Run Tests
        run:  npm run test
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  docker:
    name: Build - Docker
    runs-on: ubuntu-18.04
    needs: [ sonarcloud ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/social-share-code:latest




